### ISSUE TITLE
那个网站的demo不能用了吗？

### ISSUE THREAD

**Issue by helllyf** [str2num/libice#4]
![image](https://user-images.githubusercontent.com/19581189/70371310-63a0b580-190c-11ea-8101-8f92cb45a580.png)

**Comment by str2num** [comment]
我试了应该是可以的，注意开启摄像头和麦克风权限，输入相同的房间号，不同的uid

**Comment by helllyf** [comment]
万分感谢，开启权限就可以了

**Comment by helllyf** [comment]
解决
